### ISSUE TITLE
Bioinformatics Hub of Kenya

### ISSUE THREAD

**Issue by Fnyasimi** [open-life-science/ols-1#2]
# Mission
To bridge the gap between well established and aspiring bioinformaticians through peer training and mentorship so as to enhance collaborations to foster quality scientific research and innovations and promote the sharing of data, skills and codes.

# Vision
To be a vivacious, well-coordinated and enthusiastic hub that will develop bioinformatics and skills set through creating awareness, collaborations and capacity development.

**Comment by bebatut** [comment]
@Fnyasimi would it be possible for you to re-create an issue for your project. We created a template for the issue and it just got deployed. Sorry for the inconvenience.

**Comment by Fnyasimi** [comment]
@bebatut I have done so

**Comment by bebatut** [comment]
Thanks a lot!
